# distrobox assemble create --file ini/python_postgres.ini --name python --replace
[python]
image=docker.io/library/ubuntu:22.04
pull=true
additional_packages="git build-essential python3-dev python3-venv python3-pip libpq-dev telnet postgresql-client"
nvidia=false
start_now=true
init_hooks="pip install --upgrade pip"
init_hooks="pip install --upgrade setuptools"
# Distrobox automatically mounts home
# volume="/home/perryr/proj:/home/perryr/proj"